name: tobiasvetter
favicon: null
layout_spectrum: 0
typography_spectrum: 0.89836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-58154788-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92a0b9'
    - '#fffeff'
    - '#37629d'
    - '#cfd5e5'
    - '#17315b'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
