typography_spectrum: 0.9324492791201919
color:
  brandColors:
    - '#92a0b9'
    - '#fffeff'
    - '#37629d'
    - '#cfd5e5'
    - '#17315b'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45472
analytics:
  google: UA-58154788-3
  facebook: null
  twitter: null
name: tobiasvetter
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: tobiasvetter
purpose: []
